name: Neurospecation
description: AI Review Bot
author: Lars Lawoko

inputs:
  review:
    description: 'Add "pr" to run a Pull request review'
    required: false
  debug:
    description: 'Add -d to debug'
    required: false
  token:
    description: 'GH token, must have write access to add comment for review'
    required: false
    default: ${{ github.token }}
runs:
  using: docker
  image: Dockerfile
  args:
    - "${{ inputs.debug }}"
    - "${{ inputs.review }}"