name: Neurospecation
description: AI Review Bot
author: Lars Lawoko

inputs:
  command_args:
    description: 'Command line arguments'
    required: false
    default: '-r'
  token:
    description: 'GH token, must have write access to add comment for review'
    required: false
    default: ${{ github.token }}
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.command_args }}