name: PR Review

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  PRReview:
    name: Neurospection PR Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures we have full history

      - name: Fetch target branch
        run: |
          TARGET_BRANCH="${{ github.base_ref }}"  # Use the PR's base branch
          echo "Fetching target branch: $TARGET_BRANCH"
          git fetch origin $TARGET_BRANCH
          git branch --track $TARGET_BRANCH origin/$TARGET_BRANCH || true

      - name: Debug Git Environment
        run: |
          echo "Checking if we are inside a Git repo..."
          pwd
          ls -la
          git rev-parse --is-inside-work-tree || echo "Not a git repo"
          git status || echo "Git status failed"
          git branch -a || echo "git branch failed"
          git remote -v || echo "git remote -v failed"
          git diff main || echo "git diff main failed"
          git diff main...HEAD || echo "git diff main...HEAD failed"
        shell: bash

      - name: Test Local Action
        id: test-action
        uses: ./ # TODO: once published to the store, use the proper version
        with:
          debug: "-d"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_PR_NUMBER: ${{ github.event.number }}
