name: PR Review

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: write  # Allow write access to issues for commenting

jobs:
  PRReview:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          debug: "-d"
          review: "-r"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}